<?php
include('C:\xampp\htdocs\ydf-system-oshen\app\views\fpdf\fpdf.php');

class PDF extends FPDF
{
    // Header
    function Header()
    {
        // Company Info
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 6, 'YOUR DAILY FOODS (PVT) LTD', 0, 1, 'C');
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 6, "No. 22, St. Anthony's Mawatha, Kanuwana, Ekala, Ja-Ela, Sri Lanka", 0, 1, 'C');
        $this->Ln(4);

        
    }

    // Footer
    function Footer()
    {
        // Bank Info
        $this->SetFont('Arial', '', 9);
        $this->MultiCell(0, 5, "BANK: Hatton National Bank PLC\nBRANCH: Ja-Ela Branch\nACCOUNT NUMBER: 087910206029\nSWIFT CODE: HBLILKLX\nBANK ADDRESS: No. 73, Old Negombo Road, Kanuwana, Ja-Ela, Sri Lanka", 0, 'C');
        $this->Ln(5);

        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by Your Daily Foods System', 0, 0, 'C');
    }
}

// Create new PDF
$pdf = new PDF();
$pdf->AddPage();

// ============ INVOICE HEADER DETAILS ============
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 10, 'INVOICE', 0, 1, 'C');
$pdf->Ln(3);

// Consignee details
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 6, 'CONSIGNEE: NEITHAL FRESH SEAFOOD LLC', 0, 1);
$pdf->Cell(0, 6, '6262 PENDRAGON PL, JACKSONVILLE, FL 32258, USA', 0, 1);
$pdf->Cell(0, 6, 'Tel: 904-874-8890', 0, 1);
$pdf->Ln(5);

// Invoice info
$pdf->Cell(0, 6, 'DATE: 26.08.2025', 0, 1);
$pdf->Cell(0, 6, 'INV NO: YDF/NFS/005/25', 0, 1);
$pdf->Cell(0, 6, 'AWB NO: 176-0921-6852', 0, 1);
$pdf->Cell(0, 6, 'FLIGHT DETAILS: EK-651 / EK-219', 0, 1);
$pdf->Cell(0, 6, 'DESTINATION: Orlando (MCO) - USA', 0, 1);
$pdf->Cell(0, 6, 'FDA REG NO: 17245219874', 0, 1);
$pdf->Cell(0, 6, 'TOTAL BOXES: 22', 0, 1);
$pdf->Ln(8);

// ============ TABLE HEADER ============
$pdf->SetFont('Arial', 'B', 9);
$pdf->SetFillColor(230, 230, 230);
$pdf->Cell(10, 8, '#', 1, 0, 'C', true);
$pdf->Cell(30, 8, 'Description', 1, 0, 'C', true);
$pdf->Cell(40, 8, 'Scientific Name', 1, 0, 'C', true);
$pdf->Cell(20, 8, 'Weight (Kg)', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Unit Price', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Value (USD)', 1, 1, 'C', true);

// ============ TABLE DATA (Example Items) ============
$pdf->SetFont('Arial', '', 9);
$items = [
    ['Trevally Steak', 'Caranx spp.', '14.14', '20.00', '282.80'],
    ['Barramundi Steak', 'Lates calcarifer', '11.19', '21.60', '241.70'],
    ['Emperor Steak', 'Lethrinus spp.', '12.52', '19.50', '244.14'],
    ['Red Snapper Steak', 'Lutjanus spp.', '1.48', '21.40', '31.67'],
    ['King Fish Steak', 'Scomberomorus commerson', '50.62', '27.00', '1366.74']
];

$total = 0;
foreach ($items as $i => $item) {
    $pdf->Cell(10, 8, $i + 1, 1, 0, 'C');
    $pdf->Cell(30, 8, $item[0], 1, 0);
    $pdf->Cell(40, 8, $item[1], 1, 0);
    $pdf->Cell(20, 8, $item[2], 1, 0, 'R');
    $pdf->Cell(25, 8, $item[3], 1, 0, 'R');
    $pdf->Cell(25, 8, $item[4], 1, 1, 'R');
    $total += $item[4];
}

// ============ TOTAL ============
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(125, 8, 'TOTAL (USD)', 1, 0, 'R');
$pdf->Cell(25, 8, number_format($total, 2), 1, 1, 'R');
$pdf->Ln(10);

// Declaration
$pdf->SetFont('Arial', '', 9);
$pdf->MultiCell(0, 6, "The exporter LKREX102891600DC0841 of the products covered by this document declares that, except where otherwise clearly indicated, these products are of Origin Sri Lanka preferential origin according to rules of origin of the Generalized System of Preferences of the EU and that the origin criterion met is 'P'.");

// Output
$pdf->Output('I', 'Invoice_YDF_NFS_005_25.pdf');

?>